public/libs/views.js
Fix https://github.com/atomery/webcatalog/issues/853
=> Fix cannot read property 'startsWith' of undefined

package.json, public/libs/updater.js, yarn.lock
Replace GitHub API with GitHub Release Feed
=> Fix updater fails as GitHub API requests exceed server limit (2)

package.json, src/components/dialog-preferences/index.js, src/components/dialog-preferences/list-item-default-browser.js, src/components/dialog-preferences/list-item-default-mail-client.js, yarn.lock
Resolve https://github.com/atomery/webcatalog/issues/784
=> Fix unable to set app as default mail client and browser on Windows 10

public/libs/create-menu.js
Resolve https://github.com/atomery/webcatalog/issues/882
=> Fix zoom menu item isn't working on Windows & Linux

public/libs/workspaces.js
https://github.com/atomery/webcatalog/issues/905#issuecomment-659404697
=> Fix "type error: cannot convert undefined or null to object" bug

package.json, public/libs/views.js, yarn.lock
Resolve https://github.com/atomery/webcatalog/issues/913
=> Fix window is unexpectedly focused on Linux

src/components/main/index.js
Related to https://github.com/atomery/webcatalog/issues/905
=> Replace animated progress with loading text to save CPU

public/electron.js, public/libs/views.js
Resolve https://github.com/atomery/webcatalog/issues/955
=> Fix request not authorized (UA unmatched) bug in TT-RSS

README.md, public/libs/create-menu.js, public/preload/view.js, src/components/dialog-about/index.js, src/components/dialog-preferences/index.js
Resolve https://github.com/atomery/webcatalog/issues/971
=> Fix info/support links are not correct

public/libs/views.js
Resolve https://github.com/atomery/webcatalog/issues/908
=> Add Yandex Mail & FastMail badge support

package.json, public/libs/views.js, yarn.lock
Resolve https://github.com/atomery/webcatalog/issues/542
=> Add in-app PDF reader

package.json, public/libs/views.js, yarn.lock
Resolve https://github.com/atomery/webcatalog/issues/992
=> Fix 'remote' is undefined in BrowserView preload script

public/libs/views.js, public/preload/view.js
Resolve https://github.com/atomery/webcatalog/issues/994
=> Disable context isolation temporarily to fix WASM-related bug

public/libs/views.js
This fixes https://github.com/atomery/webcatalog/issues/870
=> Fix BrowserView sometimes becomes draggable

public/preload/view.js
Resolve https://github.com/atomery/webcatalog/issues/993
=> Fix DarkReader doesn't handle images correctly

public/windows/main.js
https://github.com/maxogden/menubar/issues/296
=> Fix dock icon is not hidden when attaching to menubar

public/libs/views.js
Fix https://github.com/atomery/webcatalog/issues/1007
=> Fix page keeps reloading after signing in with Google

public/libs/workspaces-views.js
Also fix cannot read property 'id' of undefined
=> Fix cannot read property 'getBrowserView' of null

public/libs/create-menu.js
Fix https://github.com/atomery/webcatalog/issues/1015
Related: https://github.com/electron/electron/issues/5256
=> Fix Cmd+ to zoom in doesn't work with non-US keyboard

public/constants/mailto-urls.js
Resolve https://github.com/atomery/webcatalog/issues/1008
=> Add Office 365 Outlook support

public/libs/views.js
Resolve https://github.com/atomery/webcatalog/issues/996
=> Fix Microsoft internal URLs are not detected correctly

public/libs/preferences.js, public/preload/view.js, src/components/dialog-preferences/index.js, src/constants/auto-refresh-intervals.js
Resolve https://github.com/atomery/webcatalog/issues/891
=> Add option to reload web pages automatically

patches/darkreader+4.9.17.patch, patches/node-fetch+2.6.1.patch, public/preload/view.js
Fix https://github.com/atomery/webcatalog/issues/1024
=> Fix Dark Reader cannot access a cross-origin resource

public/libs/workspaces.js
Resolve https://github.com/atomery/webcatalog/issues/1036
=> Fix shared browsing data is removed when starting app

public/libs/workspaces.js
=> Fix shared browsing data is not retained when quitting app (2)

public/windows/display-media.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1060
=> Fix module did not self-register bug on Windows & Linux

public/libs/views.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1102
=> Fix workspace attempts to load undefined URL

README.md, package.json, public/libs/create-menu.js, public/libs/preferences.js, public/libs/views.js, public/listeners/index.js, public/preload/view.js, src/components/dialog-about/index.js, src/components/dialog-add-workspace/form.js, src/components/dialog-preferences/index.js, src/components/dialog-workspace-preferences/index.js, src/senders/index.js, src/state/dialog-code-injection/actions.js, src/state/dialog-custom-user-agent/actions.js, yarn.lock
Resolve https://github.com/webcatalog/webcatalog-app/issues/1092
=> Add option to only reload on inactivity

public/libs/get-view-bounds.js, public/windows/main.js, src/components/app-wrapper.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1138
=> Fix title bar is not hidden in full screen mode on Windows & Linux

public/libs/preferences.js, src/components/dialog-add-workspace/home.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/986
=> Add support for branded multisite apps

public/electron.js, public/libs/menu.js, public/libs/preferences.js, src/components/dialog-preferences/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1114
=> Add option to warn before quitting

public/electron.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1146
=> Fix mailto/http protocol URLs are not handled on Windows & Linux

public/libs/app-lock.js, src/components/dialog-preferences/index.js
- Follow 6c59ab0
- Disable App Lock on Linux ARM64
Related to https://github.com/atom/node-keytar/issues/318
=> Fix App Lock prevents app window from showing up on Linux ARM64 (2)

src/components/dialog-preferences/index.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1092#issuecomment-720665630
=> Fix option to only reload when inactive is disabled

public/libs/app-lock.js
Revert bf4e5556627689528d7c9646f3ed5e89bc9aa1ca
Resolved by https://github.com/atom/node-keytar/issues/318#issuecomment-727682637
=> Reenable App Lock on ARM64 Linux devices

public/libs/app-lock.js
This reverts commit 609fec9be3807f6106439d1ccbc8b389f5f7066c.
=> Revert "Reenable App Lock on ARM64 Linux devices (#202)"

README.md, src/components/dialog-add-workspace/home.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1199#issuecomment-734830862
=> Update development documentation

.github/workflows/linux-arm64.yml, .github/workflows/linux-x64.yml, .github/workflows/macos-x64.yml, .github/workflows/windows-arm64.yml, .github/workflows/windows-x64.yml, README.md
Related to https://github.com/webcatalog/webcatalog-app/issues/1194
=> Add Windows on ARM support

public/windows/main.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1201
=> Fix KDE Plasma prevents app window from minimizing

public/libs/is-kde-async.js, public/windows/main.js
=> Fix BrowserView is not restored when unminimizing on Windows

package.json, public/libs/system-preferences.js, public/windows/main.js, src/components/dialog-preferences/index.js, yarn.lock
Resolve https://github.com/webcatalog/webcatalog-app/issues/1198
=> Add option to open app at login on Linux

public/listeners/index.js, public/preload/view.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1221
=> Fix window doesn't show up when clicking on notifications on Linux

.github/workflows/linux-arm64.yml, .github/workflows/linux-x64.yml, .github/workflows/windows-x64.yml, package.json, public/libs/context-menu-builder.js, public/libs/views.js, yarn.lock
https://github.com/webcatalog/webcatalog-app/issues/1196
=> Add "Save Image As..." menu item

public/libs/views.js, public/listeners/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1233
=> Fix "Open link in New Window" menu item is not working

public/listeners/index.js, public/preload/view.js, public/windows/display-media.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1235
=> Fix display media window doesn't show up

src/components/main/index.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1247
=> Fix always-visible scroll bar breaks sidebar layout & functionality

src/components/main/draggable-region.js, src/components/main/index.js, src/components/main/navigation-bar.js, src/components/main/workspace-selector.js, src/constants/workspace-colors.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1247
=> Fix bugs related to draggable regions

.github/workflows/windows-arm64.yml, README.md
This reverts commit 4ca3c979877aa17796993d8ae82d6a6293b92dd4.
=> Revert "Remove Windows on ARM support (#233)"

package.json, yarn.lock
Fix https://github.com/webcatalog/webcatalog-app/issues/1254
Fix https://github.com/webcatalog/webcatalog-app/issues/1237
Details: https://github.com/electron/electron/issues/27131
=> Fix top area of browser view is not clickable on Windows & Linux

package.json, public/app.json, public/electron.js
https://github.com/webcatalog/webcatalog-app/issues/1284#issue-782105421
=> Store user data in the same user data directory as WebCatalog

src/components/main/navigation-bar.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1276
=> Fix spellcheck is unexpectedly enabled for URL bar

main-src/windows/main.js, patches/menubar+9.0.2.patch
Resolve https://github.com/webcatalog/webcatalog-app/issues/1336
Resolve https://github.com/webcatalog/webcatalog-app/issues/1239
=> Remember menu bar window size and position

main-src/electron.js, main-src/libs/preferences.js, src/components/dialog-preferences/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1337
=> Re-enable menu bar/taskbar mode on Windows & Linux

main-src/libs/app-lock.js
`node-keytar` has been fixed with https://github.com/atom/node-keytar/pull/352
=> Enable App Lock feature for Linux arm64

main-src/libs/views.js, main-src/windows/main.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1359
=> Fix BrowserView disappears when window is minimized for some time

patches/@cliqz+adblocker-electron+1.20.2.patch, webpack.config.js
"Error processing argument at index 0, conversion failure from"
=> Fix cosmetic filters are not loaded correctly

.github/workflows/macos-arm64.yml, build-keytar-arm64.sh, public/open-source-notices.txt
Related to https://github.com/atom/node-keytar/issues/346
=> Fix App Lock is not working on macOS ARM64

main-src/windows/preferences.js, main-src/windows/workspace-preferences.js, src/components/dialog-preferences/index.js, src/components/dialog-workspace-preferences/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1372
=> Add ability to resize preferences windows

main-src/libs/views.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/649
=> Fix Google Meet screen sharing compatibility

main-src/invokers/index.js, main-src/libs/preferences.js, main-src/libs/views.js, package.json, public/open-source-notices.txt, src/components/dialog-customize-fonts/index.js, src/components/dialog-preferences/index.js, src/invokers/index.js, src/state/dialog-customize-fonts/actions.js, yarn.lock
No stable library to get font family list.
=> Remove option to customize default font family

src/components/dialog-preferences/index.js, src/components/dialog-workspace-preferences/index.js
https://github.com/webcatalog/webcatalog-app/issues/1425
=> Open developer tools to free users

main-src/libs/view-preload.js, src/components/dialog-code-injection/index.js
https://github.com/webcatalog/webcatalog-app/issues/1425
=> Add webcatalog.setBadgeCount API

main-src/libs/get-recipe.js, main-src/libs/recipes/discord.js, main-src/libs/recipes/feedly.js, main-src/libs/recipes/gmail.js, main-src/libs/recipes/index.js, main-src/libs/recipes/instagram.js, main-src/libs/recipes/messenger.js, main-src/libs/recipes/slack.js, main-src/libs/recipes/whatsapp.js, main-src/libs/recipes/yahoo-mail.js, main-src/libs/view-preload.js, webpack.config.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1425
=> Add recipes to support badge count for popular apps

main-src/windows/main.js, src/components/shared/windows-title-bar.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1427
=> Fix browser view is not restored correctly when unminimizing from tray

main-src/electron.js, main-src/libs/preferences.js, main-src/libs/recipes/feedly.js, main-src/libs/recipes/gmail.js, main-src/libs/recipes/instagram.js, main-src/libs/recipes/yahoo-mail.js, main-src/libs/view-preload.js, main-src/libs/views.js, main-src/libs/workspace-metas.js, main-src/listeners/index.js, package.json, public/app.json, src/components/dialog-preferences/index.js, src/components/main/workspace-selector.js, src/senders/index.js, yarn.lock
https://github.com/webcatalog/webcatalog-app/issues/1434
=> Fix badge related bugs

main-src/libs/recipes/gmail.js, main-src/libs/view-preload.js
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge
=> Integrate with navigator.setAppBadge() web API

main-src/windows/go-to-url.js, main-src/windows/open-url-with.js, main-src/windows/preferences.js, main-src/windows/workspace-preferences.js
win object is set to `null` because of 'closed' event
=> Fix cannot read property 'show' of null

package.json, yarn.lock
Fix https://github.com/webcatalog/webcatalog-app/issues/1453
=> Upgrade to electron@13.1.3

src/components/main/workspace-selector.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1458
=> Grey out hibernated accounts/services

main-src/electron.js, main-src/libs/preferences.js, src/components/preferences/section-performance/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1462
=> Restore ability to hibernate inactive accounts at launch

main-src/electron.js, main-src/libs/preferences.js, src/components/open-url-with/index.js, src/components/preferences/section-link-handling/index.js, src/components/preferences/section-link-handling/list-item-open-protocol-url.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1463
=> Add selection to open links triggered by protocols in main or new window

main-src/libs/views.js, src/components/preferences/index.js
This reverts commit ffc4dd558804f17806c748eb0c85047db833342d.
=> Revert "Disable extension support in production (#537)"

main-src/windows/main.js
Close https://github.com/webcatalog/webcatalog-app/issues/1475
=> Fix swiping does not work if window attached to menu bar

main-src/electron.js, src/components/preferences/index.js
App Store Review policy is too strict.
=> Disable location support in Mac App Store builds

main-src/libs/views.js
Thanks to https://github.com/minbrowser/min/pull/1715
=> Improve Google app compatibility with better UA adjustment method

main-src/libs/view-preload.js
Thanks to https://github.com/minbrowser/min/pull/1715
=> Add navigator.userAgentData web API support

package.json, patches/electron-chrome-extensions+3.9.0.patch, yarn.lock
https://github.com/webcatalog/webcatalog-app/issues/710
=> Upgrade to electron-chrome-extensions@3.9.0

main-src/windows/main.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1509
=> Fix native title bar is not visible on Windows

main-src/windows/main.js
Fix https://github.com/webcatalog/webcatalog-app/issues/1518
=> Fix cannot read properties of undefined (reading 'getBrowserView')

main-src/windows/main.js, patches/menubar+9.0.5.patch
Resolve https://github.com/webcatalog/webcatalog-app/issues/1521
=> Fix remote module is not enabled in menu bar mode

main-src/listeners/index.js, src/components/main/sidebar.js, src/components/workspace-preferences/section-auto-reload/index.js, src/senders/index.js, src/state/dialog-refresh-interval/actions.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1572
=> Add option to reload account/service to sidebar selector

main-src/libs/view-preload/password-fill.js
=> Fix "this document requires 'TrustedHTML' assignment" error

main-src/libs/views.js
This reverts commit c2b55ba3b2ab97a82afb3eed4e4ed51565f0ab8e.
=> Revert "Fix compatibility UA logic might not be applied fully in some cases (#722)"

src/components/main/mac-title-bar.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1579
=> Fix title bar page title is not aligned centered properly

main-src/libs/preferences.js, src/components/main/mac-title-bar.js, src/components/preferences/section-view/index.js
Resolve https://github.com/webcatalog/webcatalog-app/issues/1579
=> Add option to hide navigation buttons on title bar

main-src/electron.js
https://github.com/electron/electron/issues/28422
=> [CU-29nqpwd] Fix file saving doesn't work correctly for Excalidraw and diagrams.net

main-src/libs/password-manager/keychain.js, package.json, public/open-source-notices-automated.txt, yarn.lock
Main reason: node-sqlite3 doesn't compile correctly for Linux ARM64.
=> Replace node-sqlite3 with better-sqlite3
